Customtoken draft
buidly/sc-dust-converter-rs pull request #19
Opened 2023-04-06 13:05 UTC by dragos-rebegea

2023-04-07 14:43 UTC, raress96 commented on dust-converter/src/config.rs
> +            amount >= &(debt_threshold * BigUint::from(MIN_DEBT_THRESHOLD_PERCENTAGE) / BigUint::from(MAX_PERCENTAGE)),
Not sure why we need the `MIN_DEBT_THRESHOLD_PERCENTAGE` constant.
It seems that here we check currently if amount >= 1.2 x debt_threshold, but we can just have `amount >= debt_threshold` check instead IMO.

2023-04-07 14:43 UTC, raress96 commented on dust-converter/src/config.rs
> +        if custom_token_manager_address != caller {
Why does this endpoint have different permissions then `topup_custom_token`? Shouldn't they both be accessible only to the `custom_token_manager_address`?

2023-04-07 14:43 UTC, raress96 commented on dust-converter/src/config.rs
> +    #[payable("*")]
I think this `payable` should have been added to the above endpoint not here 😄

2023-04-07 14:43 UTC, raress96 commented on dust-converter/src/config.rs
> +    fn require_token_buffer_has_debt_threshold(&self, token: &TokenIdentifier, amount: &BigUint) {
I think a better name for this would be `require_amount_passes_debt_threshold`, since there is no token_buffer actually used in this function.

2023-04-07 14:43 UTC, raress96 commented on dust-converter/src/lib.rs
> +    fn swap_dust_tokens(&self, num_wegld: usize, amount_out_min: BigUint, tag: Option<ManagedBuffer>, token_wanted: OptionalValue<TokenIdentifier>) {
Any reason why `tag` was changed from `OptionalValue` to `Option`? Curious why it wasn't left as it was.

2023-04-07 15:06 UTC, raress96 commented on dust-converter/src/config.rs
> +    fn token_buffer(&self, token: &TokenIdentifier) -> SingleValueMapper<EsdtTokenPayment<Self::Api>>;
This should also be a view so in the cronjob I can do calculations properly.

2023-04-07 15:20 UTC, raress96 commented on dust-converter/src/lib.rs
> +        if debt < threshold {
Could we here change the condition to be if `balance < threshold`? That way it will be also easier to check in the cronjob since it will not need to know the `token_buffer` size.

2023-04-07 15:41 UTC, dragos-rebegea commented on dust-converter/src/lib.rs
> +    fn swap_dust_tokens(&self, num_wegld: usize, amount_out_min: BigUint, tag: Option<ManagedBuffer>, token_wanted: OptionalValue<TokenIdentifier>) {
You cannot have 2 OptionalValue

2023-04-09 10:07 UTC, alexjilavu commented on dust-converter/src/config.rs
> +        if custom_token_manager_address != caller {
I would leave this as it is; as it allows the contract owner to withdraw if for some reason the manager can't

2023-04-09 10:32 UTC, alexjilavu requested changes
Apart from my comments, I have 2 other suggestions.
- extracting the custom token logic into it's separate module would greatly improve readability
- adding a comment to the function try_rebalance_token_buffer; explaining in natural language how it works. I find it difficult to understand.

2023-04-09 10:32 UTC, alexjilavu commented on dust-converter/src/config.rs
> +    fn token_buffer(&self, token: &TokenIdentifier) -> SingleValueMapper<EsdtTokenPayment<Self::Api>>;
You are storing an EsdtTokenPayment but never use nonce or token_id. I suggest changing it to a BigUint, storing just what you need, the amount.

2023-04-09 10:32 UTC, alexjilavu commented on dust-converter/src/lib.rs
> +    fn swap_dust_tokens(&self, num_wegld: usize, amount_out_min: BigUint, tag: Option<ManagedBuffer>, token_wanted: OptionalValue<TokenIdentifier>) {
I strongly disagree with this. I suggest making token_wanted not optional and keeping the tag as OptionalValue.
I don't know how this Option parameter behaves and don't even know if it works. But even if it works it's not a clean option.

2023-04-09 12:01 UTC, dragos-rebegea commented on dust-converter/src/config.rs
> +    fn token_buffer(&self, token: &TokenIdentifier) -> SingleValueMapper<EsdtTokenPayment<Self::Api>>;
changed to BigUint

2023-04-09 12:02 UTC, dragos-rebegea commented on dust-converter/src/lib.rs
> +    fn swap_dust_tokens(&self, num_wegld: usize, amount_out_min: BigUint, tag: Option<ManagedBuffer>, token_wanted: OptionalValue<TokenIdentifier>) {
made token_wanted mandatory, and rollback for the tag to OptionalValue

2023-04-09 12:02 UTC, dragos-rebegea commented on dust-converter/src/config.rs
> +    #[payable("*")]
done

2023-04-10 08:38 UTC, alexjilavu approved these changes

2023-04-10 13:21 UTC, raress96 commented on dust-converter/src/custom_token.rs
> +    fn token_buffer(&self, token: &TokenIdentifier) -> SingleValueMapper<BigUint>;
Add view for this mapper.

2023-05-02 11:19 UTC, merged